# Generated by Django 6.0.2 on 2026-04-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_attendance_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(unique=True),
        ),
    ]
